apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        # image: k8s.gcr.io/heapster-amd64:v1.4.2
        image: harbor.past123.com/past123/heapster-amd64:v1.4.2
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
        # start metrics api
        - --api-server=true
        - --requestheader-client-ca-file=/var/run/kubernetes/client-ca-file
        volumeMounts:
        - name: client-ca
          mountPath: /var/run/kubernetes
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: client-ca
          configMap:
            name: extension-apiserver-authentication
