apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-aws-indexer 
  namespace: logcenter 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash-aws-indexer 
    spec:
      containers:
      - name: logstash-aws-indexer 
        image: en-us-public-ops-harbor-1.360in.com:4333/pinguo/logstash-aws-indexer:v2
        resources:
          # TODO: Set memory limits when we've profiled the container for large
          # clusters, then set request = limit to keep this container in
          # guaranteed class. Currently, this container falls into the
          # "burstable" category so the kubelet doesn't backoff from restarting it.
          limits:
            memory: "13960Mi"
            cpu: "4" 
          requests:
            cpu: "0.5" 
            memory: "4048Mi"
        livenessProbe:
          exec:
            command:
            - /bin/bash 
            - -c 
            - ps -ef |grep logstash
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/bash 
            - -c 
            - ps -ef |grep docker-entrypoint 
          initialDelaySeconds: 3
          timeoutSeconds: 5
        env:
        - name: LS_HEAP_SIZE 
          value: "8g"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /data/logbak
          name: aws-storage 
          subPath: logbak-k8s
      nodeSelector:
        type: logcenter 
      imagePullSecrets:
      - name: pull-secret 
      volumes:
      - name: aws-storage 
        hostPath:
          path: /data/
          type: Directory
