apiVersion: v1
kind: Service
metadata:
  name: prometheus-blackbox-svc 
  namespace: monitoring
  annotations:
    prometheus.io/probe: 'true'
  labels:
    app: prometheus-blackbox-svc 
spec:
  ports:
    - port: 9115 
      targetPort: 9115 
      protocol: TCP
  selector:
    app: prometheus-blackbox 
