apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-config
  namespace: monitoring
data:
  config.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.exmail.qq.com:25'
      smtp_from: 'monitor@camera360.com'
      smtp_auth_username: 'monitor@camera360.com'
      smtp_auth_password: '254zQ9sVICVz'
      slack_api_url: '<slack_api_url>'
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 15m
      receiver: ops 

      routes:
      - match_re:
          ops: "yes"
        receiver: ops 
        group_by: ['alertname']
        group_wait: 30s
        group_interval: 5m 
        repeat_interval: 15m
        continue: true 
      - match_re:
          ops: "yes"
        receiver: ops-email 
        continue: true 
      - match:
          ads: "yes"
        receiver: ads
        group_by: ['alertname']
        group_wait: 30s
        group_interval: 5m 
        repeat_interval: 15m
        continue: true 
      - match:
          ads: "yes" 
        receiver: ads-email 

    receivers:
    - name: 'ops'
      webhook_configs:
      - url: 'http://34.206.84.227:8889/prometheus'
      - url: 'http://prometheus-alerta-web/api/webhooks/prometheus'
        send_resolved: true
    - name: 'ops-email'
      email_configs:
      - to: 'puqiaoming@camera360.com'
      - to: 'zhuanming@camera360.com'
        send_resolved: true

    - name: 'ads'
      webhook_configs:
      - url: 'http://34.206.84.227:8889/prometheus'
        send_resolved: true
    - name: 'ads-email'
      email_configs:
      - to: 'yangbing@camera360.com'
      - to: 'fuzhiyong@camera360.com'
      - to: 'shenqiang@camera360.com'
      - to: 'zhanglu@camera360.com'
        send_resolved: true
