apiVersion: v1
data:
  disable-ipv6: "true"
  enable-vts-status: "true"
  hsts: "false"
  ssl-redirect: "false"
#  use-proxy-protocol: "true"
  client_max_body_size: "100M"
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
