kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-home
  namespace: kube-system
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.1.12.71:8080"
  restuser: ""
  secretNamespace: ""
  secretName: ""
allowVolumeExpansion: true 
