---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-web
spec:
  rules:
  - host: monitor.past123.com
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-web
          servicePort: 80
