kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-kafka-config
  namespace: log
  labels:
    app: logstash-kafka-config
data:
  logstash-kafka.config: |-
    input {
      file {
          path                      => "/var/lib/docker/containers/*.log"
      }
    }
    output {
      kafka {
          bootstrap_servers         => ["kafka.past123.com:9094"]
          client_id                 => "logstash"
          group_id                  => "logstash"
          auto_offset_reset         => "latest"
          consumer_threads          => 2
          decorate_events           => true
          topics                    => ["k8s"]
          type                      => "k8s-cluster"
          codec                     => "json_lines"
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-kafka-pipelines
  namespace: log
  labels:
    app: logstash-kafka-pipelines
data:
  pipelines.yml: |-
    - pipeline.id: logstash-kafka
      queue.type: persisted
      pipeline.workers: 1
      path.config: "/etc/logstash/conf.d/logstash-kafka.config"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-kafka-yml
  namespace: log
  labels:
    app: logstash-kafka-yml
data:
  logstash.yml: |-
    xpack.monitoring.enabled: false
    http.port: 9600
    log.format: plain
