apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logstash-kafka
  namespace: log
  labels:
    k8s-app: logstash-kafka
    version: v6.1.2
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: logstash-kafka
      version: v6.1.2
  template:
    metadata:
      labels:
        k8s-app: logstash-kafka
        version: v6.1.2
        kubernetes.io/cluster-service: "true"
    spec:
      # 访问 /var/log/containers/* 提权到root
      securityContext:
        runAsUser: 0
      containers:
      - name: logstash-es
        # logstash用的elastic官方镜像: docker pull docker.elastic.co/logstash/logstash:6.1.2
        image: harbor.past123.com/past123/logstash:6.1.2
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - name: data
          mountPath: /usr/share/logstash/data
        - name: logstash-kafka-config
          mountPath: /etc/logstash/conf.d
          readOnly: true
        - name: logstash-kafka-yml
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          #readOnly: true
        - name: logstash-kafka-pipelines
          mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
        # docker log
        - name: varlibdockercontainers
          mountPath: /data/docker/containers
          readOnly: true
        # pod log link
        - name: podloglink
          mountPath: /var/log/containers
          readOnly: true
        # pod log
        - name: podlog
          mountPath: /var/log/pods
          readOnly: true
        env:
          - name: XPACK_MONITORING_ENABLED
            value: "false"
          - name: LOG_LEVEL
            value: "info"
        ports:
        - containerPort: 9600
          name: metrics
          protocol: TCP
      volumes:
      - name: data
        emptyDir: {}
      - name: logstash-kafka-config
        configMap:
          defaultMode: 0766
          name: logstash-kafka-config
      - name: logstash-kafka-yml
        configMap:
           defaultMode: 0766
           name: logstash-kafka-yml
      - name: logstash-kafka-pipelines
        configMap:
           defaultMode: 0766
           name: logstash-kafka-pipelines
      - name: varlibdockercontainers
        hostPath:
          path: /data/docker/containers
      - name: podloglink
        hostPath:
          path: /var/log/containers
      - name: podlog
        hostPath:
          path: /var/log/pods
      imagePullSecrets:
        - name: regsecret
