kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-kafka-config
  namespace: log
  labels:
    app: logstash-kafka-config
data:
  logstash-kafka.config: |-
    input {
      file {
          path                      => "/var/log/containers/*.log"
          exclude                   => ["nginx-ingress-*.log","kibana-logging-*"]
      }
    }
    output {
      kafka {
          #bootstrap_servers         => "kafka.past123.com:9094"
          bootstrap_servers         => "kafka-svc:9094"
          topic_id                  => "k8s"
          codec                     => "json_lines"
          compression_type          => "gzip"
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-kafka-pipelines
  namespace: log
  labels:
    app: logstash-kafka-pipelines
data:
  pipelines.yml: |-
    - pipeline.id: logstash-kafka
      queue.type: persisted
      pipeline.workers: 1
      path.config: "/etc/logstash/conf.d/logstash-kafka.config"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-kafka-yml
  namespace: log
  labels:
    app: logstash-kafka-yml
data:
  logstash.yml: |-
    xpack.monitoring.enabled: false
    http.port: 9600
    log.format: plain
