apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: prometheus-deployment
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      # 指定pod以用户id=0 运行
      securityContext:
        runAsUser: 0
      serviceAccountName: prometheus
      containers:
      - image: harbor.past123.com/past123/prometheus:v1.0
        name: prometheus
        command:
        - "/bin/prometheus"
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention=24h"
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: "/prometheus"
          name: prometheus-storage
          subPath: prometheus-storage
        - mountPath: "/etc/prometheus"
          name: config-volume
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
        securityContext:
          allowPrivilegeEscalation: false
      imagePullSecrets:
      - name: regsecret
      volumes:
      - configMap:
          name: prometheus-config
        name: config-volume
      # 指定node挂载/data为挂载目录
      - hostPath:
          path: /data
          type: Directory
        name: prometheus-storage
      # 指定pod到固定node
      nodeSelector:
        task: monitor
