apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-es
  namespace: log
  labels:
    k8s-app: logstash-es
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: logstash-es
  template:
    metadata:
      labels:
        k8s-app: logstash-es
    spec:
      containers:
      - name: logstash-es
        # logstash用的elastic官方镜像: docker pull docker.elastic.co/logstash/logstash:6.1.2
        image: harbor.past123.com/past123/logstash:6.1.2
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - name: data
          mountPath: /usr/share/logstash/data
        - name: logstash-config
          mountPath: /etc/logstash/conf.d
          readOnly: true
        - name: logstash-yml
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          #readOnly: true
        - name: logstash-pipelines
          mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
        env:
          - name: XPACK_MONITORING_ENABLED
            value: "false"
          - name: LOG_LEVEL
            value: "info"
        ports:
        - containerPort: 9600
          name: metrics
          protocol: TCP
      volumes:
      - name: data
        emptyDir: {}
      - name: logstash-config
        configMap:
          defaultMode: 0766
          name: logstash-config
      - name: logstash-yml
        configMap:
           defaultMode: 0766
           name: logstash-yml
      - name: logstash-pipelines
        configMap:
           defaultMode: 0766
           name: logstash-pipelines
      imagePullSecrets:
        - name: regsecret
