apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  name: prometheus-deployment-alertmanager
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-alertmanager
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: prometheus-k8s
      containers:
      - image: prom/alertmanager 
        name: prometheus-alertmanager
        command:
        - "/bin/alertmanager"
        args:
        - "-config.file=/etc/alertmanager/config.yml"
        - "-storage.path=/alertmanager"
        - "-web.external-url=https://en-us-alert.360in.com"
        ports:
        - containerPort: 9093
          protocol: TCP
        volumeMounts:
        - mountPath: "/alertmanager"
          name: prometheus-storage
          subPath: promethtus-alert-storage
        - mountPath: "/etc/alertmanager"
          name: config-volume
        resources:
          requests:
            cpu: 300m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
      volumes:
      - name: prometheus-storage 
        hostPath:
          path: /data/
          type: Directory
      - configMap:
          name: prometheus-alert-config
        name: config-volume
      nodeSelector:
        monitor: admit 
