apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc 
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: prometheus-svc 
spec:
  type: NodePort
  ports:
    - port: 9096 
      targetPort: 9090
      nodePort: 32097
      protocol: TCP
  selector:
    app: prometheus 
