apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: prometheus-blackbox-deployment
  name: prometheus-blackbox
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-blackbox
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9115'
    spec:
      serviceAccountName: prometheus-k8s
      containers:
      - image: prom/blackbox-exporter 
        name: prometheus-blackbox
        ports:
        - containerPort: 9115 
          #hostPort: 9090
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 800m
            memory: 800Mi
      nodeSelector:
        monitor: admit
