apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage 
  namespace: monitoring 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 88Gi
  storageClassName: glusterfs
